version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"  # Isso mapeia a porta serial para o contêiner
    privileged: true  # Isso permite acesso total ao dispositivo
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: telemetry
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

